apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rag-dec19-1
  janus-idp.io/tekton: rag-dec19-1
  backstage.io/kubernetes-id: rag-dec19-1
  backstage.io/kubernetes-namespace: rag-dec19-1 
  app.kubernetes.io/part-of: rag-dec19-1
resources: 
- initialize-namespace.yaml
- deployment-model-server.yaml
- service-model-server.yaml
- deployment.yaml
- route.yaml
- service.yaml
- model-config.yaml
- deployment-database.yaml
- service-database.yaml
- database-config.yaml
